orchard_create_draft:
    path:     /draft
    defaults: { _controller: OrchardBundle:Create:draft }

orchard_create_steps:
    path:     /steps/{id_orchard}
    defaults: { _controller: OrchardBundle:Create:steps, id_orchard:null }

orchard_create_step:
    path:     /step/{step_orchard}/{id_orchard}
    defaults: { _controller: OrchardBundle:Create:step, step:11, id_orchard:null }

orchard_create_insert:
    path:     /insert/{id_orchard}
    defaults: { _controller: OrchardBundle:Create:insert, id_orchard:null }

orchard_create_insert_checkbox:
    path:     /insert/checkbox/{id_orchard}/{entity}
    defaults: { _controller: OrchardBundle:Create:checkbox, id_orchard:null }

orchard_create_publish:
    path:     /publish/{id_orchard}/{publish}
    defaults: { _controller: OrchardBundle:Create:publish, id_orchard:null, publish:false }
