#Todas las rutas en este archivo tienen como prefix /orchard

#Ruta utilizada para redirigir a un paso en concreto de la creación de un huerto
#Recibe el id del huerto que se está creando mediante el método GET (el número del paso al que se redirigirá se gestiona según este id)
orchard_create_id:
    path:     /create
    defaults: { _controller: OrchardBundle:Default:index }

#Ruta utilizada para redirigir a un paso en concreto de la creación un huerto
#Recibe el número del paso al que se quiere acceder (por defecto al primero) mediante el método GET
orchard_create_step:
    path:     /step/{step}
    defaults: { _controller: OrchardBundle:Default:create, step:11 }

#Ruta utilizada para insertar un huerto en la BBDD
#Recibe los campos del formulario correspondiente mediante el método POST
orchard_insert:
    path:     /insert
    defaults: { _controller: OrchardBundle:Default:insert }

#Ruta utilizada para enviar un mail de sugerencia al administrador
#Recibe la sugerencia del paso 1.4 de la creación de un huerto mediante el método GET
orchard_send:
    path:     /send/{orchard_type}
    defaults: { _controller: OrchardBundle:Default:send }

#Ruta utilizada para aceptar una sugerencia de tipo de huerto desde un mail
#Recibe la sugerencia y si ésta ha sido acceptada o no mediante el método GET
orchard_suggest:
    path:     /suggest/{orchard_type}/{accept}
    defaults: { _controller: OrchardBundle:Default:suggest, accept:false }

#Ruta utilizada para guardar una imagen de huerto
#Recibe una imagen y la guarda en BBDD mediante el método POST
orchard_uploadImages:
    path:     /images/upload
    defaults: { _controller: OrchardBundle:Default:uploadImage}

orchard_deleteImages:
    path:     /images/delete/{idImage}
    defaults: { _controller: OrchardBundle:Default:deleteImage,idImage:null}

orchard_modifyImages:
    path:     /images/modify/{idImage}
    defaults: { _controller: OrchardBundle:Default:modifyImage,idImage:null}
#Ruta utilizada para guardar un fichero de ormar de huerto
#Recibe un fichero en un formato valido y lo guarda como fichero en la carpeta
orchard_uploadFiles:
    path:     /files/upload
    defaults: {_controller: OrchardBundle:Default:uploadFile}
