orchard_create:
    path:     /create
    defaults: { _controller: OrchardBundle:Default:index }
orchard_create_step:
    path:     /create/step
    defaults: { _controller: OrchardBundle:Default:create }
orchard_insert:
    path:     /insert
    defaults: { _controller: OrchardBundle:Default:insert }
