orchard_upload_images_upload:
    path:     /images/upload/{id_orchard}
    defaults: { _controller: OrchardBundle:Upload:uploadImage, id_orchard:null}

orchard_upload_images_favourite:
    path:     /images/favourite/{id_orchard}/{id_image}/{favourite}
    defaults: { _controller: OrchardBundle:Upload:favourite, id_orchard:null, id_image:null}

orchard_upload_images_delete:
    path:     /images/delete/{idImage}
    defaults: { _controller: OrchardBundle:Upload:deleteImage, idImage:null}

orchard_upload_images_modify:
    path:     /images/modify/{idImage}
    defaults: { _controller: OrchardBundle:Upload:modifyImage, idImage:null}

###ficheros normas
orchard_upload_files_upload:
    path:     /files/upload/{id_orchard}
    defaults: {_controller: OrchardBundle:Upload:uploadFile, id_orchard:null}

orchard_upload_files_delete:
    path:     /files/delete/{id_orchard}
    defaults: {_controller: OrchardBundle:Upload:deleteFile, id_orchard:null}
