orchard_uploadImages:
    path:     /images/upload/{id_orchard}
    defaults: { _controller: OrchardBundle:Upload:uploadImage, id_orchard:null}

orchard_deleteImages:
    path:     /images/delete/{idImage}
    defaults: { _controller: OrchardBundle:Upload:deleteImage,idImage:null}

orchard_modifyImages:
    path:     /images/modify/{idImage}
    defaults: { _controller: OrchardBundle:Upload:modifyImage,idImage:null}

orchard_uploadFiles:
    path:     /files/upload
    defaults: {_controller: OrchardBundle:Upload:uploadFile}
