orchard_create_steps:
    path:     /create/steps/{id_orchard}
    defaults: { _controller: OrchardBundle:Create:steps, id_orchard:null }

orchard_create_step:
    path:     /create/step/{step_orchard}/{id_orchard}
    defaults: { _controller: OrchardBundle:Create:step, step:11, id_orchard:null }

orchard_insert:
    path:     /create/insert/{id_orchard}
    defaults: { _controller: OrchardBundle:Create:insert, id_orchard:null }

orchard_preview:
    path:     /create/preview/{id_orchard}
    defaults: {_controller: OrchardBundle:Create:preview, id_orchard:null}
