orchard_create:
    path:     /create
    defaults: { _controller: OrchardBundle:Default:index, id_orchard:null }
orchard_create_id:
    path:     /create/{id_orchard}
    defaults: { _controller: OrchardBundle:Default:index, id_orchard:null }

orchard_create_step:
    path:     /step/{step}
    defaults: { _controller: OrchardBundle:Default:create, step:11 }

orchard_insert:
    path:     /insert
    defaults: { _controller: OrchardBundle:Default:insert }
