user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

orchard:
    resource: "@OrchardBundle/Resources/config/routing.yml"
    prefix:   /orchard

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
