# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
     app.form.registration:
         class: UserBundle\Form\UserType
         arguments: [%fos_user.model.user.class%]
         tags:
             -  { name: form.type, alias:app_user_registration }
     app.locale_listener:
         class: HomeBundle\EventListener\LocaleListener
         arguments: ['%kernel.default_locale%']
         tags:
             -  { name: kernel.event_subscriber }
     twig.extension.sortbyfield:
         class: Snilius\Twig\SortByFieldExtension
         tags:
             - { name: twig.extension }
     app.provider.oauth:
         class: UserBundle\Security\Core\User\OAuthUserProvider
         arguments: ['@fos_user.user_manager', {facebook: facebookID, google: googleID}]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
