home_homepage:
    path:     /{_locale}
    defaults: { _controller: HomeBundle:Home:index, _locale: es }
    requirements:
        _locale: en|es|ca

home_find:
    path:     /find
    defaults: { _controller: HomeBundle:Search:find }
