home_homepage:
    path:     /{_locale}
    defaults: { _controller: HomeBundle:Home:index, _locale: es }
    requirements:
        _locale: en|es|ca

home_why:
    path:     /why/{action}
    defaults: { _controller: HomeBundle:Home:why }

home_how:
    path:     /how/{action}
    defaults: { _controller: HomeBundle:Home:how }

home_find_orchard:
    path:     /find/orchard
    defaults: { _controller: HomeBundle:Search:findOrchard }

home_find_event:
    path:     /find/event
    defaults: { _controller: HomeBundle:Search:findEvent }
