event_create_list:
    path:     /create/list
    defaults: { _controller: EventBundle:Create:list }

event_create_orchard:
    path:     /create/orchard/{id_orchard}
    defaults: { _controller: EventBundle:Create:orchard, id_orchard:null }

event_create:
    path:     /create/{id_event}/{id_orchard}
    defaults: { _controller: EventBundle:Create:create, id_event:null, id_orchard:null  }

event_create_inscribed:
    path:     /create/list/inscribed/{id_event}
    defaults: { _controller: EventBundle:Create:inscribed, id_event:null }

event_create_inscribed_delete:
    path:     /create/list/inscribed/delete/{id_event}/{id_user}
    defaults: { _controller: EventBundle:Create:deleteInscribed, id_event:null, id_user:null }

event_show_profile:
    path:     /show/profile/{id_event}/{search}
    defaults: { _controller: EventBundle:Show:profile, id_event:null , search:null}

event_add_user:
    path:     /add/userevent/{id_event}/{amount}
    defaults: { _controller: EventBundle:Show:addUserToEvent, id_event:null }
