event_create_list:
    path:     /create/list
    defaults: { _controller: EventBundle:Create:list }

event_create_orchard:
    path:     /create/orchard/{id_orchard}
    defaults: { _controller: EventBundle:Create:orchard, id_orchard:null }

event_create:
    path:     /create
    defaults: { _controller: EventBundle:Create:create }

event_show_profile:
    path:     /profile/{id_orchard}
    defaults: { _controller: EventBundle:Show:profile, id_orchard:null }
