event_create:
    path:     /create/{id_orchard}
    defaults: { _controller: EventBundle:Create:create, id_orchard:null }

event_show_profile:
    path:     /profile/show/{id_event}
    defaults: { _controller: EventBundle:Show:profile, id_event:null }
